# Generated by Django 6.0.7 on 2026-07-31 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dataset_anomaly_count_dataset_anomaly_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_value', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='myapp.dataset')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['dataset', 'timestamp'], name='myapp_forec_dataset_f2e9d4_idx')],
            },
        ),
    ]
