# Generated by Django 6.0.7 on 2026-08-30 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_dataset_contamination_dataset_target_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('machine_type', models.CharField(choices=[('pc', 'Personal Computer'), ('cnc', 'CNC Machine'), ('compressor', 'Compressor'), ('pump', 'Pump'), ('motor', 'Electric Motor'), ('other', 'Other')], default='pc', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('predicted_watts', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_forecasts', to='myapp.machine')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='myapp_energ_machine_c914a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('rca_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('rca_results', models.JSONField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtime_events', to='myapp.machine')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['machine', 'start_time'], name='myapp_downt_machine_f38acb_idx')],
            },
        ),
        migrations.CreateModel(
            name='MachineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_usage_percent', models.FloatField(blank=True, null=True)),
                ('cpu_temp_celsius', models.FloatField(blank=True, null=True)),
                ('ram_usage_percent', models.FloatField(blank=True, null=True)),
                ('disk_read_mbps', models.FloatField(blank=True, null=True)),
                ('disk_write_mbps', models.FloatField(blank=True, null=True)),
                ('net_sent_mbps', models.FloatField(blank=True, null=True)),
                ('net_recv_mbps', models.FloatField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('battery_percent', models.FloatField(blank=True, null=True)),
                ('estimated_power_watts', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='myapp.machine')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='myapp_machi_machine_e9bd53_idx')],
                'constraints': [models.UniqueConstraint(fields=('machine', 'timestamp'), name='unique_machine_timestamp')],
            },
        ),
    ]
